import type { CSSProperties, ImgHTMLAttributes } from 'react';
// @ts-expect-error generated by build.mjs: { '/images/...': data URL }
import EMBEDDED from 'balibu:assets';

// Stand-in for next/image outside Next.js: a plain <img>. Site images come
// embedded; other root-relative paths load from the repo's public/ folder on
// GitHub, pinned to the commit the bundle was built from (__ASSET_BASE__).
declare const __ASSET_BASE__: string;
const embedded = EMBEDDED as Record<string, string>;

type Src = string | { src: string; width?: number; height?: number };
type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, 'src'> & {
  src: Src;
  fill?: boolean;
  priority?: boolean;
  quality?: number;
  placeholder?: string;
  blurDataURL?: string;
  unoptimized?: boolean;
};

export default function Image({ src, fill, priority, quality, placeholder, blurDataURL, unoptimized, style, ...rest }: Props) {
  const raw = typeof src === 'string' ? src : src.src;
  const url = embedded[raw] ?? (raw.startsWith('/') && !raw.startsWith('//') ? __ASSET_BASE__ + raw : raw);
  const fillStyle: CSSProperties | undefined = fill
    ? { position: 'absolute', inset: 0, width: '100%', height: '100%' }
    : undefined;
  return (
    <img
      {...rest}
      src={url}
      style={{ ...fillStyle, ...style }}
    />
  );
}
